### ISSUE TITLE
Not handling any changes

### ISSUE THREAD

**Issue by vinaySaxo** [jcgertig/react-mutation-observer#3]
I am using something like this

<MutationObserver onContentChange={this.handleMutation}>
                {
                    !_.isEmpty(this.data) &&
                    <BootstrapTable data={this.data} striped condensed hover>
                        {this.generateHeaders()}
                    </BootstrapTable>
                }
            </MutationObserver>

what i want is whenver this.data changes over some socket connection, the column inside bootstraptable(which is a 3rd party plugin) updates, this should fire handleMutation event.

**Comment by vinaySaxo** [comment]
Currently it is not firing event.

**Comment by jcgertig** [comment]
This is only for dom mutations
