### ISSUE TITLE
Helper Components destroy and mount again child component

### ISSUE THREAD

**Issue by gitowiec** [jcgertig/react-mutation-observer#4]
MutationObserver,  WatchChildren,  WatchForChildrenRemoval,  WatchForChildrenAddition
All of them make my component trigger componentDidMount and componentWillUnmount more than needed, this makes rereading props in the constructor. I can't reuse my component within whole React lifecycle.

**Comment by owen-m1** [comment]
Why is this closed? I have the same issue
